// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKHOMECITYITEMTRACES_H__
#define __CLOCKHOMECITYITEMTRACES_H__

#define KOstTraceComponentID 0x2002bce6

#define CLOCKHOMECITYITEM_CLOCKHOMECITYITEM_ENTRY 0x8a0024
#define CLOCKHOMECITYITEM_CLOCKHOMECITYITEM_EXIT 0x8a0025
#define DUP1_CLOCKHOMECITYITEM_CLOCKHOMECITYITEM_ENTRY 0x8a0026
#define DUP1_CLOCKHOMECITYITEM_CLOCKHOMECITYITEM_EXIT 0x8a0027
#define CLOCKHOMECITYITEM_SETHOMECITYITEMDATA_ENTRY 0x8a0028
#define CLOCKHOMECITYITEM_SETHOMECITYITEMDATA_EXIT 0x8a0029


#endif

// End of file

