// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENEDITORDOCLOADERTRACES_H__
#define __CALENEDITORDOCLOADERTRACES_H__

#define KOstTraceComponentID 0x10207198

#define CALENEDITORDOCLOADER_CALENEDITORDOCLOADER_ENTRY 0x8a0103
#define CALENEDITORDOCLOADER_CALENEDITORDOCLOADER_EXIT 0x8a0104
#define DUP1_CALENEDITORDOCLOADER_CALENEDITORDOCLOADER_ENTRY 0x8a0105
#define DUP1_CALENEDITORDOCLOADER_CALENEDITORDOCLOADER_EXIT 0x8a0106
#define CALENEDITORDOCLOADER_CREATEOBJECT_ENTRY 0x8a0107


#endif

// End of file

