// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __ALARMALERTDOCLOADERTRACES_H__
#define __ALARMALERTDOCLOADERTRACES_H__

#define KOstTraceComponentID 0xe3ae7edb

#define ALARMALERTDOCLOADER_ALARMALERTDOCLOADER_ENTRY 0x8a0001
#define ALARMALERTDOCLOADER_ALARMALERTDOCLOADER_EXIT 0x8a0002
#define DUP1_ALARMALERTDOCLOADER_ALARMALERTDOCLOADER_ENTRY 0x8a0003
#define DUP1_ALARMALERTDOCLOADER_ALARMALERTDOCLOADER_EXIT 0x8a0004
#define ALARMALERTDOCLOADER_CREATEOBJECT_ENTRY 0x8a0005
#define ALARMALERTDOCLOADER_CREATEOBJECT_EXIT 0x8a0006


#endif

// End of file

