// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __AGENDAEVENTVIEWERDOCLOADERTRACES_H__
#define __AGENDAEVENTVIEWERDOCLOADERTRACES_H__

#define KOstTraceComponentID 0x2002c367

#define AGENDAEVENTVIEWERDOCLOADER_CREATEOBJECT_ENTRY 0x8a0075
#define AGENDAEVENTVIEWERDOCLOADER_CREATEOBJECT_EXIT 0x8a0076
#define DUP1_AGENDAEVENTVIEWERDOCLOADER_CREATEOBJECT_EXIT 0x8a0077


#endif

// End of file

