// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __AGENDAEVENTVIEWERITEMTRACES_H__
#define __AGENDAEVENTVIEWERITEMTRACES_H__

#define KOstTraceComponentID 0x2002c367

#define AGENDAEVENTVIEWERITEM_AGENDAEVENTVIEWERITEM_ENTRY 0x8a0078
#define AGENDAEVENTVIEWERITEM_AGENDAEVENTVIEWERITEM_EXIT 0x8a0079
#define DUP1_AGENDAEVENTVIEWERITEM_AGENDAEVENTVIEWERITEM_ENTRY 0x8a007a
#define DUP1_AGENDAEVENTVIEWERITEM_AGENDAEVENTVIEWERITEM_EXIT 0x8a007b
#define AGENDAEVENTVIEWERITEM_SETEVENTVIEWERITEMDATA_ENTRY 0x8a007c
#define AGENDAEVENTVIEWERITEM_SETEVENTVIEWERITEMDATA_EXIT 0x8a007d


#endif

// End of file

